module.exports = {
    urlSmallGym: '192.168.68.106', //add "http://" infront
    urlLargeGym: '192.168.68.105', //add "http://" infront
    smallGymEffect: '',
    largeGymEffect: '',
    pincode: '5678',
    effectsSmallGym: [
        { name: 'OFF', key: '1', num: 'A=S1P1' },
        { name: 'Flashing tubes', key: '2', num: 'A=S1P2' },
        { name: 'NL Flag', key: '3', num: 'A=S1P3' },
        { name: 'Color Scroll', key: '4', num: 'A=S1P4' },
        { name: 'Red w/white effect', key: '5', num: 'A=S1P5' },
        { name: 'Strobing lines', key: '6', num: 'A=S1P6' },
        { name: 'Red w/color bounce', key: '7', num: 'A=S1P7' },
        { name: 'Fast plasma', key: '8', num: 'A=S1P8' },
        { name: 'Yellow/Orange color fade', key: '9', num: 'A=S1P9' },
        { name: 'Blue fades', key: '10', num: 'A=S1P10' },
        { name: 'Rainbow sideways', key: '11', num: 'A=S1P11' },
        { name: 'Slow yellow chase', key: '12', num: 'A=S1P12' },
        { name: 'Flashing yellow lines', key: '13', num: 'A=S1P13' },
        { name: 'Static rainbow', key: '14', num: 'A=S1P14' },
        { name: 'Yellow dots', key: '15', num: 'A=S1P15' },
        { name: 'Slow color change', key: '16', num: 'A=S1P16' },
        { name: 'fireworks', key: '17', num: 'A=S1P17' },
        { name: 'fireworks', key: '18', num: 'A=S1P18' },
        { name: 'fireworks', key: '19', num: 'A=S1P19' },
        { name: 'fireworks', key: '20', num: 'A=S1P20' },
        { name: 'Red blue fireworks', key: '21', num: 'A=S1P21' },
        { name: 'Fast dots', key: '22', num: 'A=S1P22' },
        { name: 'Pink', key: '23', num: 'A=S1P23' },
        { name: 'White', key: '24', num: 'A=S1P24' },
        { name: 'Orange', key: '25', num: 'A=S1P25' },
        { name: 'Slow lava', key: '26', num: 'A=S1P26' },
        { name: 'Red fireworks', key: '27', num: 'A=S1P27' },
        { name: 'Yellow/Orange', key: '28', num: 'A=S1P28' },
        { name: 'Orange/DeepOrange', key: '29', num: 'A=S1P29' },
        { name: 'Blue', key: '30', num: 'A=S1P30' },
        { name: 'Lime', key: '31', num: 'A=S1P31' },
        { name: 'Green', key: '32', num: 'A=S1P32' },
        { name: 'White', key: '33', num: 'A=S1P33' },
        { name: 'Music: Red/Blue', key: '34', num: 'B=S2P1' },
        { name: 'Music: Equalizer', key: '35', num: 'B=S2P2' },
        { name: 'Music: Yellow/WhiteStrobe', key: '36', num: 'B=S2P3' },
        { name: 'Music: Blue/PinkDots', key: '37', num: 'B=S2P4' },
        { name: 'Music: Pink/WhiteFireworks', key: '38', num: 'B=S2P5' },
        { name: 'Music: Yellow Fill', key: '39', num: 'B=S2P6' },
        { name: 'Music: White LinesStrobe', key: '40', num: 'B=S2P7' },
        { name: 'Music: Blue/Yellow dots', key: '41', num: 'B=S2P8' },
        { name: 'Music: Colourful fill', key: '42', num: 'B=S2P9' },
        { name: 'Music: Blue/White dots', key: '43', num: 'B=S2P10' },
    
    ],
    effectsLargeGym: [
        { name: 'Dark Purple', key: '1', num: 'A=S1P1' },
        { name: 'Slow Yellow Fireworks', key: '2', num: 'A=S1P2' },
        { name: 'Yellow Strobe', key: '3', num: 'A=S1P3' },
        { name: 'Red/Blue Siren', key: '4', num: 'A=S1P4' },
        { name: 'Purple/Green Pulse', key: '5', num: 'A=S1P5' },
        { name: 'Yellow/Orange Siren', key: '6', num: 'A=S1P6' },
        { name: 'Yellow/Orange Slow', key: '7', num: 'A=S1P7' },
        { name: 'Blue w/White Pulse', key: '8', num: 'A=S1P8' },
        { name: 'Green FX Up', key: '9', num: 'A=S1P9' },
        { name: 'Sides Color Changing', key: '10', num: 'A=S1P10' },
        { name: 'Red/White Fireworks', key: '11', num: 'A=S1P11' },
        { name: 'Red w/White stars', key: '12', num: 'A=S1P12' },
        { name: 'Blue w/Red dots', key: '13', num: 'A=S1P13' },
        { name: 'Cyan Fade FX', key: '14', num: 'A=S1P14' },
        { name: 'Green/Blue FX', key: '15', num: 'A=S1P15' },
        { name: 'Red/White strobe', key: '16', num: 'A=S1P16' },
        { name: 'Red w/Green FX', key: '17', num: 'A=S1P17' },
        { name: 'Dark purple w/BlueRed FX', key: '18', num: 'A=S1P18' },
        { name: 'Fast Blue/White Siren', key: '19', num: 'A=S1P19' },
        { name: 'Pink/Red Lava', key: '20', num: 'A=S1P20' },
        { name: 'Blue/White Flashing', key: '21', num: 'A=S1P21' },
        { name: 'Red dots FX #1', key: '22', num: 'A=S1P22' },
        { name: 'Red dots FX #2', key: '23', num: 'A=S1P23' },
        { name: 'Bouncing Red', key: '24', num: 'A=S1P24' },
        { name: 'Flashing Sides White', key: '25', num: 'A=S1P25' },
        { name: 'Sides Fire FX', key: '26', num: 'A=S1P26' },
        { name: 'White Tubes FX', key: '27', num: 'A=S1P27' },
        { name: 'Static Rainbow', key: '28', num: 'A=S1P28' },
        { name: 'fireworks', key: '29', num: 'A=S1P29' },
        { name: 'Orange w/Blue FX', key: '30', num: 'A=S1P30' },
        { name: 'Red/Yellow Siren', key: '31', num: 'A=S1P31' },
        { name: 'Red/Pink/Blue Lava', key: '32', num: 'A=S1P32' },
        { name: 'Green/Red Siren', key: '33', num: 'A=S1P33' },
        { name: 'Rainbow Siren', key: '34', num: 'A=S1P34' },
        { name: 'Slow Gold Chase', key: '35', num: 'A=S1P35' },
        { name: 'Strobing Red/White', key: '36', num: 'A=S1P36' },
        { name: 'Cyan Effect', key: '37', num: 'A=S1P37' },
        { name: 'Static Red', key: '38', num: 'A=S1P38' },
        { name: 'Static Green', key: '39', num: 'A=S1P39' },
        { name: 'Static Blue', key: '40', num: 'A=S1P40' },
        { name: 'Static Orange', key: '41', num: 'A=S1P41' },
        { name: 'Bouncing Red Ceiling', key: '42', num: 'A=S1P42' },
        { name: 'Blue w/White stars', key: '43', num: 'A=S1P43' },
        { name: 'Glowing Sides', key: '44', num: 'A=S1P44' },
        { name: 'Red Dots', key: '45', num: 'A=S1P45' },
        { name: 'Slow Red Siren', key: '46', num: 'A=S1P46' },
        { name: 'Blue/Green Fade', key: '47', num: 'A=S1P47' },
        { name: 'Slow Red/Orange Fade', key: '48', num: 'A=S1P48' },
        { name: 'Lava', key: '49', num: 'A=S1P49' },
        { name: 'Rainbow Ceiling', key: '50', num: 'A=S1P50' },
        { name: 'White Tones Fade', key: '51', num: 'A=S1P51' },
        { name: 'Orange fade', key: '52', num: 'A=S1P52' },
        { name: 'Green sides / Purple FX', key: '53', num: 'A=S1P53' },
        { name: 'Slow Siren', key: '54', num: 'A=S1P54' },
        { name: 'White', key: '55', num: 'A=S1P55' },
        { name: 'Blue', key: '56', num: 'A=S1P56' },
        { name: 'Yellow sides / Blue FX', key: '57', num: 'A=S1P57' },
        { name: 'Static White/Pink', key: '58', num: 'A=S1P58' },
        { name: 'Purple sides / Yellow FX', key: '59', num: 'A=S1P59' },
        { name: 'Red w/Rainbow Ceiling', key: '60', num: 'A=S1P60' },
    ],
};
